name: Start Telegraf
description: Use testnet-deploy to start the Telegraf service on all VMs
inputs:
  ansible-forks:
    description: The number of forks, or parallel connections, to use with Ansible. Defaults to 50.
  custom-inventory:
    description: >
      Run the start telegraf playbook against particular VMs in the environment.
      Should be a comma-separated list.
      Cannot be used with the node-type input.
  network-name:
    description: The name of the network
    required: true
  node-type:
    description: >
      Specify the type of node VM to start the telegraf services on. If not provided, the telegraf services on
      all the node VMs will be started. Valid values are "bootstrap", "genesis", "generic" and "private".
      Cannot be used with the custom-inventory input.

runs:
  using: composite
  steps:
    - name: start telegraf
      env:
        ANSIBLE_FORKS: ${{ inputs.ansible-forks }}
        CUSTOM_INVENTORY: ${{ inputs.custom-inventory }}
        NETWORK_NAME: ${{ inputs.network-name }}
        NODE_TYPE: ${{ inputs.node-type }}
      shell: bash
      run: |
        set -e

        cd sn-testnet-deploy
        command="testnet-deploy start-telegraf --name $NETWORK_NAME "
        [[ -n $ANSIBLE_FORKS ]] && command="$command --forks $ANSIBLE_FORKS "
        [[ -n $NODE_TYPE ]] && command="$command --node-type $NODE_TYPE "

        if [[ -n $CUSTOM_INVENTORY ]]; then
          IFS=',' read -ra VM_NAMES <<< "$CUSTOM_INVENTORY"
          for vm_name in "${VM_NAMES[@]}"; do
            command="$command --custom-inventory $vm_name"
          done
        fi

        echo "Will run testnet-deploy with: $command"
        eval $command
